version: '3'
services:
  node:
    image: alexeygorbachevskiyy/node
    build: .
    restart: on-failure
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      PORT: ${PORT}
    volumes:
      - ./src:/usr/app/src
      - ./logs:/usr/app/logs
    networks:
      - custom_net
  postgres:
    container_name: postgres
    image: alexeygorbachevskiyy/postgres
    build: ./src/db/
    restart: on-failure
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - custom_net
networks:
  custom_net:
    driver: bridge
volumes:
  pgdata:
